### ISSUE TITLE
Issues when compiling again.

### ISSUE THREAD

**Issue by TheChymera** [neurolabusc/surf-ice#2]
Hi, I remember we left this as "sometimes it builds, sometimes it doesn't". Which was fine since if I tried a few times, I would get it to build.

I am trying to install surf-ice on a new machine now, and I have tried to build it over 10 times. it keeps failing. [Here's a sample error message](http://bpaste.net/show/e5abb2f41410).

Can you help me out?

**Comment by neurolabusc** [comment]
Sorry, an issue with the development branch. For the moment, use one of the stable releases or add specify the gtk2 widgetset... 
  --ws=gtk2
I will fix this shortly, it is an issue of needing the Cocoa widgetset on MacOS.

**Comment by neurolabusc** [comment]
Should be fixed for good now. Try the current master

**Comment by TheChymera** [comment]
Still fails, with afaict the same error message. Reproduced [this](http://bpaste.net/show/31070e0d2a9b) 5 times in a row. This doesn't seem to spontaneously build any more.

**Comment by neurolabusc** [comment]
Why don't you try again, the current master now compiles out of the box on CentOS to both OpenGL 3.3 Core (if opts.inc has the line "{$DEFINE COREGL}" uncommented) or to OpenGL 2.1. Please make sure you have refreshed your source code (e.g. "git pull"), as Cocoa is no longer specified. I do not have a Gentoo distribution, so it is hard for me to troubleshoot.

You can also test the pre-compiled executables from
  https://github.com/neurolabusc/surf-ice/releases/edit/v1.0.20170202

**Comment by TheChymera** [comment]
Ok, it works now, by which I mean the objective-c error is gone, but I still get the access violation mandelbug. Here's a sample of how it once failed and worked (based on the exact same source code): https://bpaste.net/show/f9f6f28922a4 .

**Comment by neurolabusc** [comment]
I am afraid I can not be of much help, as I do not use Debian-based distributions and have never seen similar errors on CentOS (or Windows or MacOS). Just looking at the file, it looks like you are always doing a lot of recompiling, whereas I would have thought you only need to rebuild the IDE if there are packages missing. My MRIcroGL page describes how to detect if the packages are missing and to only rebuild if required
  https://github.com/neurolabusc/MRIcroGL
this might help you out, as the problem appears to occur when compiling the package pascalscript. It would certainly speed up compilation for users who want both MRIcroGL and Surf Ice, which have the same package dependencies. Perhaps @yarikoptic or @mih can help as they are Debian experts.

**Comment by TheChymera** [comment]
Debian is entirely distinct from Gentoo. In Gentoo packages are always built from source on the machine which wants to have them installed - so I would assume that I'm compiling *everything*. I don't know whether this will help shed more light on the issue, though.
